spring:
  jpa:
    #    open-in-view: false
    database: mysql
    show-sql: false
    hibernate:
      ddl-auto: update
    properties.hibernate:
      dialect: org.hibernate.dialect.MySQL8Dialect
      jdbc.lob.non_contextual_creation: true

  datasource:
    platform: mysql
    url: jdbc:mysql://localhost:3306/harvest
    username:
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver


local.server.port: 4140

server:
  port: 4140
  ssl:
    enabled: false
    key-store-type: PKCS12
    key-store:
    key-alias:
    key-store-password:
  servlet:
    session.timeout: 10m
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 2MB
      max-request-size: 2MB
  tomcat:
    accept-count: 1000 # Maximum queue length for incoming connection requests when all possible request processing threads are in use.
    max-connections: 1000 # Maximum number of connections that the server accepts and processes at any given time.
    max-threads: 1000 # Maximum amount of worker threads.
    min-spare-threads: 10 # Minimum amount of worker threads.
    uri-encoding: UTF-8 # Character encoding to use to decode the URI.

ethparser:
  web3Url:
  stubPrice: true


